// react-forum/resources/js/Pages/Posts/Partials/CommentEditModal.vue
<script setup>
import { useForm } from "@inertiajs/vue3";
import Modal from "@/Components/Modal.vue";
import PrimaryButton from "@/Components/PrimaryButton.vue";

const props = defineProps({
    comment: { type: Object, required: true },
});

const form = useForm({
    content: props.comment.content,
});

const show = defineModel("show");

const submit = () => {
    form.put(route("comment.update", { comment: props.comment }), {
        onSuccess: () => (show.value = false),
    });
};
</script>

<template>
    <Modal :show="show" @close="show = false">
        <form @submit.prevent="submit" class="mt-4">
            <textarea
                v-model="form.content"
                class="w-full p-2 mb-2 border rounded"
                placeholder="Skomentuj..."
            ></textarea>
            <PrimaryButton> Zapisz </PrimaryButton>
        </form>
    </Modal>
</template>

// react-forum/resources/js/Pages/Posts/Partials/CommentEditModal.jsx
import React, { useState, useEffect } from "react";
import { useForm } from "@inertiajs/react";
import Modal from "@/Components/Modal";
import PrimaryButton from "@/Components/PrimaryButton";

const CommentEditModal = ({ comment, show, setShow }) => {
    const form = useForm({
        content: comment.content,
    });

    const submit = (e) => {
        e.preventDefault();
        form.put(route("comment.update", { comment }), {
            onSuccess: () => setShow(false),
        });
    };

    return (
        <Modal show={show} onClose={() => setShow(false)}>
            <form onSubmit={submit} className="mt-4">
                <textarea
                    value={form.data.content}
                    onChange={(e) => form.setData("content", e.target.value)}
                    className="w-full p-2 mb-2 border rounded"
                    placeholder="Skomentuj..."
                ></textarea>
                <PrimaryButton> Zapisz </PrimaryButton>
            </form>
        </Modal>
    );
};

export default CommentEditModal;
