// vue-forum/resources/js/Pages/Posts/Partials/PostEditModal.vue
<script setup>
import { ref } from "vue";
import { useForm } from "@inertiajs/vue3";
import Modal from "@/Components/Modal.vue";
import InputLabel from "@/Components/InputLabel.vue";
import TextInput from "@/Components/TextInput.vue";
import Multiselect from "@/Components/Multiselect.vue";
import PrimaryButton from "@/Components/PrimaryButton.vue";

const props = defineProps({
    post: { type: Object, required: true },
    tags: { type: Array, required: true },
    categories: { type: Array, required: true },
});

const form = useForm({
    title: props.post.title,
    content: props.post.content,
    tags: props.post.tags,
    categories: props.post.categories,
});

const show = defineModel("show");
</script>

<template>
    <Modal :show @close="show = false">
        <form
            @submit.prevent="submit"
            class="flex justify-center px-4 sm:px-6 lg:px-8 mt-24"
        >
            <div class="w-full max-w-md">
                <h1 class="text-3xl font-bold text-center mb-8">
                    Edycja postu
                </h1>

                <div>
                    <InputLabel for="title" value="Tytuł" required />

                    <TextInput
                        id="title"
                        type="text"
                        class="mt-1 block w-full"
                        v-model="form.title"
                        required
                        autofocus
                    />
                </div>

                <div class="mt-4">
                    <InputLabel for="content" value="Treść" required />

                    <textarea
                        id="content"
                        class="mt-1 block w-full h-72 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                        required
                        v-model="form.content"
                        autofocus
                    ></textarea>
                </div>

                <div class="mt-4">
                    <InputLabel
                        for="category"
                        value="Wybierz kategorie"
                        required
                    />

                    <Multiselect
                        :options="categories"
                        v-model="form.categories"
                    />
                </div>

                <div class="mt-4">
                    <InputLabel for="tags" value="Wybierz tagi" required />

                    <Multiselect :options="tags" v-model="form.tags" />
                </div>

                <div class="flex items-center justify-end mt-4">
                    <PrimaryButton
                        class="ms-4"
                        :class="{ 'opacity-25': form.processing }"
                        :disabled="form.processing"
                    >
                        Zapisz
                    </PrimaryButton>
                </div>
            </div>
        </form>
    </Modal>
</template>

// react-forum/resources/js/Pages/Posts/Partials/PostEditModal.jsx
import React, { useState, useEffect } from "react";
import { useForm } from "@inertiajs/react";
import Modal from "@/Components/Modal";
import InputLabel from "@/Components/InputLabel";
import TextInput from "@/Components/TextInput";
import Multiselect from "@/Components/Multiselect";
import PrimaryButton from "@/Components/PrimaryButton";

const PostEditModal = ({ post, tags, categories }) => {
    const cleanCategories = (categories) => {
        return categories.map(({ pivot, ...rest }) => rest);
    };

    const cleanTags = (tags) => {
        return tags.map(({ pivot, ...rest }) => rest);
    };

    const cleanedCategories = cleanCategories(post.categories);
    const cleanedTags = cleanTags(post.tags);

    const form = useForm({
        title: post.title,
        content: post.content,
        tags: cleanedTags,
        categories: cleanedCategories,
    });

    const [show, setShow] = useState(false);

    const submit = () => {
        form.put(route("posts.update", { post }), {
            onSuccess: () => setShow(false),
        });
    };

    return (
        <Modal show={show} onClose={() => setShow(false)}>
            <form
                onSubmit={submit}
                className="flex justify-center px-4 sm:px-6 lg:px-8 mt-24"
            >
                <div className="w-full max-w-md">
                    <h1 className="text-3xl font-bold text-center mb-8">
                        Edycja postu
                    </h1>

                    <div>
                        <InputLabel htmlFor="title" value="Tytuł" required />

                        <TextInput
                            id="title"
                            type="text"
                            className="mt-1 block w-full"
                            value={form.data.title}
                            onChange={(e) =>
                                form.setData("title", e.target.value)
                            }
                            required
                            autoFocus
                        />
                    </div>

                    <div className="mt-4">
                        <InputLabel htmlFor="content" value="Treść" required />

                        <textarea
                            id="content"
                            className="mt-1 block w-full h-72 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                            required
                            value={form.data.content}
                            onChange={(e) =>
                                form.setData("content", e.target.value)
                            }
                        ></textarea>
                    </div>

                    <div className="mt-4">
                        <InputLabel
                            htmlFor="category"
                            value="Wybierz kategorie"
                            required
                        />

                        <Multiselect
                            options={categories}
                            value={form.data.categories}
                            onChange={(value) =>
                                form.setData("categories", value)
                            }
                        />
                    </div>

                    <div className="mt-4">
                        <InputLabel
                            htmlFor="tags"
                            value="Wybierz tagi"
                            required
                        />

                        <Multiselect
                            options={tags}
                            value={form.data.tags}
                            onChange={(value) => form.setData("tags", value)}
                        />
                    </div>

                    <div className="flex items-center justify-end mt-4">
                        <PrimaryButton
                            className={`ms-4 ${
                                form.processing ? "opacity-25" : ""
                            }`}
                            disabled={form.processing}
                        >
                            Zapisz
                        </PrimaryButton>
                    </div>
                </div>
            </form>
        </Modal>
    );
};

export default PostEditModal;
