// react-forum/resources/js/Pages/Posts/Create.jsx
import React from "react";
import { useForm, Head } from "@inertiajs/react";
import AppLayout from "@/Layouts/AppLayout";
import Multiselect from "../../Components/Multiselect";
import InputLabel from "@/Components/InputLabel";
import TextInput from "@/Components/TextInput";
import PrimaryButton from "@/Components/PrimaryButton";

const Create = ({ categories, tags }) => {
    const { data, setData, post, processing } = useForm({
        title: "",
        content: "",
        tags: [],
        categories: [],
    });

    const handleSubmit = (e) => {
        e.preventDefault();
        post(route("posts.store"));
    };

    return (
        <AppLayout>
            <Head title="Dodaj nowy post" />

            <form
                onSubmit={handleSubmit}
                className="flex justify-center px-4 sm:px-6 lg:px-8 mt-24"
            >
                <div className="w-full max-w-md">
                    <h1 className="text-3xl font-bold text-center mb-8">
                        Dodaj nowy post
                    </h1>

                    <div>
                        <InputLabel htmlFor="title" value="Tytuł" required />
                        <TextInput
                            id="title"
                            type="text"
                            className="mt-1 block w-full"
                            value={data.title}
                            onChange={(e) => setData("title", e.target.value)}
                            required
                            autoFocus
                        />
                    </div>

                    <div className="mt-4">
                        <InputLabel htmlFor="content" value="Treść" required />
                        <textarea
                            id="content"
                            className="mt-1 block w-full h-72 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                            value={data.content}
                            onChange={(e) => setData("content", e.target.value)}
                            required
                        ></textarea>
                    </div>

                    <div className="mt-4">
                        <InputLabel
                            htmlFor="category"
                            value="Wybierz kategorie"
                            required
                        />
                        <Multiselect
                            options={categories}
                            model={data.categories}
                            setModel={(selectedCategories) =>
                                setData("categories", selectedCategories)
                            }
                        />
                    </div>

                    <div className="mt-4">
                        <InputLabel
                            htmlFor="tags"
                            value="Wybierz tagi"
                            required
                        />
                        <Multiselect
                            options={tags}
                            model={data.tags}
                            setModel={(selectedTags) =>
                                setData("tags", selectedTags)
                            }
                        />
                    </div>

                    <div className="flex items-center justify-end mt-4">
                        <PrimaryButton className="ms-4" disabled={processing}>
                            Dodaj
                        </PrimaryButton>
                    </div>
                </div>
            </form>
        </AppLayout>
    );
};

export default Create;

// vue-forum/resources/js/Pages/Posts/Create.vue
<script setup>
import AppLayout from "@/Layouts/AppLayout.vue";
import Multiselect from "../../Components/Multiselect.vue";
import { useForm, Head } from "@inertiajs/vue3";
import InputLabel from "@/Components/InputLabel.vue";
import TextInput from "@/Components/TextInput.vue";
import PrimaryButton from "@/Components/PrimaryButton.vue";

defineProps({
    categories: Array,
    tags: Array,
});

const form = useForm({
    title: "",
    content: "",
    tags: [],
    categories: [],
});

const submit = () => {
    form.post(route("posts.store"));
};
</script>

<template>
    <AppLayout>
        <Head title="Dodaj nowy post" />

        <form
            @submit.prevent="submit"
            class="flex justify-center px-4 sm:px-6 lg:px-8 mt-24"
        >
            <div class="w-full max-w-md">
                <h1 class="text-3xl font-bold text-center mb-8">
                    Dodaj nowy post
                </h1>

                <div>
                    <InputLabel for="title" value="Tytuł" />

                    <TextInput
                        id="title"
                        type="text"
                        class="mt-1 block w-full"
                        v-model="form.title"
                        required
                        autofocus
                    />
                </div>

                <div class="mt-4">
                    <InputLabel for="content" value="Treść" />

                    <textarea
                        id="content"
                        class="mt-1 block w-full h-72 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                        required
                        v-model="form.content"
                        autofocus
                    ></textarea>
                </div>

                <div class="mt-4">
                    <InputLabel for="category" value="Wybierz kategorie" />

                    <Multiselect
                        :options="categories"
                        v-model="form.categories"
                    />
                </div>

                <div class="mt-4">
                    <InputLabel for="tags" value="Wybierz tagi" />

                    <Multiselect :options="tags" v-model="form.tags" />
                </div>

                <div class="flex items-center justify-end mt-4">
                    <PrimaryButton
                        class="ms-4"
                        :class="{ 'opacity-25': form.processing }"
                        :disabled="form.processing"
                    >
                        Dodaj
                    </PrimaryButton>
                </div>
            </div>
        </form>
    </AppLayout>
</template>
