// vue-forum/resources/js/Pages/Auth/ForgotPassword.vue
<script setup>
import AppLayout from "@/Layouts/AppLayout.vue";
import InputLabel from "@/Components/InputLabel.vue";
import PrimaryButton from "@/Components/PrimaryButton.vue";
import TextInput from "@/Components/TextInput.vue";
import { Head, useForm } from "@inertiajs/vue3";

defineProps({
    status: {
        type: String,
    },
});

const form = useForm({
    email: "",
});

const submit = () => {
    form.post(route("password.email"));
};
</script>

<template>
    <AppLayout>
        <Head title="Odzyskaj hasło" />

        <div class="mb-4 text-sm text-gray-600">
            Zapomniałeś hasła? Nie ma problemu. Podaj nam swój adres e-mail, a
            wyślemy Ci link do resetowania hasła, który pozwoli Ci wybrać nowe.
        </div>

        <div v-if="status" class="mb-4 font-medium text-sm text-green-600">
            {{ status }}
        </div>

        <form @submit.prevent="submit">
            <div>
                <InputLabel for="email" value="Email" />

                <TextInput
                    id="email"
                    type="email"
                    class="mt-1 block w-full"
                    v-model="form.email"
                    required
                    autofocus
                    autocomplete="username"
                />
            </div>

            <div class="flex items-center justify-end mt-4">
                <PrimaryButton
                    :class="{ 'opacity-25': form.processing }"
                    :disabled="form.processing"
                >
                    Resetuj hasło
                </PrimaryButton>
            </div>
        </form>
    </AppLayout>
</template>

// react-forum/resources/js/Pages/Auth/ForgotPassword.jsx
import AppLayout from "@/Layouts/AppLayout";
import InputLabel from "@/Components/InputLabel";
import PrimaryButton from "@/Components/PrimaryButton";
import TextInput from "@/Components/TextInput";
import { Head, useForm } from "@inertiajs/react";

export default function ForgotPassword({ status }) {
    const { data, setData, post, processing, errors } = useForm({
        email: "",
    });

    const submit = (e) => {
        e.preventDefault();

        post(route("password.email"));
    };

    return (
        <AppLayout>
            <Head title="Odzyskaj hasło" />

            <div className="mb-4 text-sm text-gray-600">
                Zapomniałeś hasła? Nie ma problemu. Podaj nam swój adres e-mail,
                a wyślemy Ci link do resetowania hasła, który pozwoli Ci wybrać
                nowe.
            </div>

            {status && (
                <div className="mb-4 font-medium text-sm text-green-600">
                    {status}
                </div>
            )}

            <form onSubmit={submit}>
                <div>
                    <InputLabel for="email" value="Email" />

                    <TextInput
                        id="email"
                        type="email"
                        name="email"
                        value={data.email}
                        className="mt-1 block w-full"
                        isFocused={true}
                        onChange={(e) => setData("email", e.target.value)}
                    />
                </div>

                <div className="flex items-center justify-end mt-4">
                    <PrimaryButton className="ms-4" disabled={processing}>
                        Resetuj hasło
                    </PrimaryButton>
                </div>
            </form>
        </AppLayout>
    );
}
