// react-forum/resources/js/Components/Pagination.jsx
import { useEffect } from "react";
import { router } from "@inertiajs/react";

const Pagination = ({ posts }) => {
    performance.mark("PaginationStartRender");

    useEffect(() => {
        performance.mark("PaginationEndRender");

        const measure = performance.measure(
            "PaginationMeasureRender",
            "PaginationStartRender",
            "PaginationEndRender"
        );
        console.log(
            `Total time for Pagination render: ${measure.duration} ms, component complexity: 2`
        );
    }, []);
    return (
        posts.last_page > 1 && (
            <div className="pagination flex justify-center items-center mt-8">
                {posts.links.map((link) => (
                    <button
                        key={link.label}
                        className={`px-3 py-1 rounded focus:outline-none mx-1 ${
                            link.url
                                ? "bg-white text-black"
                                : "bg-gray-300 text-gray-500 cursor-not-allowed"
                        } ${
                            link.active
                                ? "border-solid border-2 border-gray-200"
                                : ""
                        }`}
                        onClick={() => link.url && router.visit(link.url)}
                        disabled={!link.url}
                        dangerouslySetInnerHTML={{ __html: link.label }}
                    />
                ))}
            </div>
        )
    );
};

export default Pagination;

// vue-forum/resources/js/Components/Pagination.vue
<script setup>
import { onBeforeMount, onMounted } from "vue";
import { router } from "@inertiajs/vue3";
defineProps({
    posts: { type: Object, required: true },
});

onBeforeMount(() => {
    performance.mark("PaginationStartRender");
});

onMounted(() => {
    performance.mark("PaginationEndRender");

    const measure = performance.measure(
        "PaginationMeasureRender",
        "PaginationStartRender",
        "PaginationEndRender"
    );
    console.log(`Total time for Pagination render: ${measure.duration} ms, 
component complexity: 2`);
});
</script>

<template>
    <div
        v-if="posts.last_page > 1"
        class="pagination flex justify-center items-center mt-8"
    >
        <template v-for="link in posts.links" :key="link.label">
            <button
                v-if="link.url"
                class="px-3 py-1 bg-white text-black rounded focus:outline-none mx-1"
                :class="{
                    'border-solid border-2 border-gray-200': link.active,
                }"
                @click="router.visit(link.url)"
            >
                <span v-html="link.label" />
            </button>
            <button
                v-else
                class="px-3 py-1 bg-gray-300 text-gray-500 rounded cursor-not-allowed mx-1"
                disabled
            >
                <span v-html="link.label" />
            </button>
        </template>
    </div>
</template>
