// react-forum/resources/js/Components/PostSearchInput.jsx
import React, { useState, useEffect, useRef } from "react";
import { Link, router } from "@inertiajs/react";
import Spinner from "./Spinner";
import PrimaryButton from "./PrimaryButton";

const SearchComponent = ({ className = "" }) => {
    const [results, setResults] = useState(null);
    const [search, setSearch] = useState("");
    const [isFocused, setIsFocused] = useState(false);
    const [loading, setLoading] = useState(true);
    const searchHtml = useRef(null);

    let timeout = useRef(null);

    const target = (post) => {
        return route("posts.show", { post });
    };

    const onFocus = () => {
        setIsFocused(true);
    };

    const onFocusOut = () => {
        setIsFocused(false);
    };

    useEffect(() => {
        setLoading(true);
        clearTimeout(timeout.current);
        timeout.current = setTimeout(() => {
            fetch(route("api.posts.index", { search }))
                .then((res) => res.json())
                .then((res) => {
                    setResults(res);
                    setLoading(false);
                });
        }, 250);
    }, [search]);

    performance.mark("PostSearchInputStartRender");

    useEffect(() => {
        performance.mark("PostSearchInputEndRender");

        const measure = performance.measure(
            "PostSearchInputMeasureRender",
            "PostSearchInputStartRender",
            "PostSearchInputEndRender"
        );
        console.log(
            `Total time for PostSearchInput render: ${measure.duration} ms, component complexity: 3`
        );
    }, []);

    return (
        <div
            ref={searchHtml}
            className={`relative ${
                isFocused && search.length > 0 ? "search--open" : ""
            } ${className}`}
        >
            {isFocused && search.length > 0 && (
                <div
                    className="fixed inset-0 bg-gray-500 bg-opacity-75 z-50"
                    onClick={onFocusOut}
                />
            )}
            <div className="relative mt-2 z-50">
                <input
                    value={search}
                    onChange={(e) => setSearch(e.target.value)}
                    placeholder="Wyszukaj post (tytuł, zawartość)"
                    className="w-full p-3 border border-gray-300 rounded focus:outline-none"
                    type="search"
                    onFocus={onFocus}
                />
            </div>
            {isFocused && search.length > 0 && (
                <div
                    className="absolute top-full left-0 w-full bg-white shadow-lg rounded z-50 p-4"
                    onBlur={onFocusOut}
                    onWheel={(e) => e.preventDefault()}
                    onTouchMove={(e) => e.preventDefault()}
                >
                    {!loading ? (
                        results?.data?.length > 0 ? (
                            <div className="flex flex-col gap-4">
                                {results.data.map((post) => (
                                    <Link key={post.id} href={target(post)}>
                                        {post.title}
                                    </Link>
                                ))}
                            </div>
                        ) : (
                            <div>Niestety nic nie znaleźliśmy</div>
                        )
                    ) : (
                        <Spinner />
                    )}
                    <div className="mt-4 flex flex-col sm:flex-row gap-2">
                        <PrimaryButton
                            className="sm:mr-2"
                            onClick={() => router.visit(route("posts.index"))}
                        >
                            Pokaż wszystkie posty
                        </PrimaryButton>
                        <PrimaryButton onClick={onFocusOut}>
                            Anuluj
                        </PrimaryButton>
                    </div>
                </div>
            )}
        </div>
    );
};

export default SearchComponent;

// vue-forum/resources/js/Components/PostSearchInput.vue
<script setup>
import { ref, watch, onBeforeMount, onMounted } from "vue";
import { Link, router } from "@inertiajs/vue3";
import Spinner from "./Spinner.vue";
import PrimaryButton from "./PrimaryButton.vue";

const results = ref();
const search = ref("");
const isFocused = ref(false);
const loading = ref(true);
const searchHtml = ref();

let timeout;

function target(post) {
    return route("posts.show", { post });
}

function onFocus() {
    isFocused.value = true;
}

function onFocusOut() {
    isFocused.value = false;
}

watch(search, (search) => {
    loading.value = true;
    clearTimeout(timeout);
    timeout = setTimeout(() => {
        fetch(route("api.posts.index", { search }))
            .then((res) => res.json())
            .then((res) => {
                results.value = res;
                loading.value = false;
            });
    }, 250);
});

onBeforeMount(() => {
    performance.mark("PostSearchInputStartRender");
});

onMounted(() => {
    performance.mark("PostSearchInputEndRender");

    const measure = performance.measure(
        "PostSearchInputMeasureRender",
        "PostSearchInputStartRender",
        "PostSearchInputEndRender"
    );
    console.log(
        `Total time for PostSearchInput render: ${measure.duration} ms, 
component complexity: 3`
    );
});
</script>

<template>
    <div
        ref="searchHtml"
        :class="{ 'search--open': isFocused && search?.length > 0 }"
        class="relative"
    >
        <transition name="fade">
            <div
                v-if="isFocused && search?.length > 0"
                class="fixed inset-0 bg-gray-500 bg-opacity-75 z-50"
                @click.stop="onFocusOut"
            />
        </transition>
        <div class="relative mt-2 z-50">
            <input
                v-model="search"
                placeholder="Wyszukaj post (tytuł, zawartość)"
                class="w-full p-3 border border-gray-300 rounded focus:outline-none"
                type="search"
                @focus="onFocus"
            />
        </div>
        <transition name="fade">
            <div
                v-if="isFocused && search?.length > 0"
                class="absolute top-full left-0 w-full bg-white shadow-lg rounded z-50 p-4"
                @focusout="onFocusOut"
                @wheel.prevent
                @touchmove.prevent
            >
                <template v-if="!loading">
                    <div
                        v-if="results?.data?.length > 0"
                        class="flex flex-col gap-4"
                        @focusout.stop="void 0"
                    >
                        <Link v-for="post in results.data" :href="target(post)">
                            {{ post.title }}
                        </Link>
                    </div>
                    <div v-else>Niestety nic nie znaleźliśmy</div>
                </template>
                <Spinner v-else />
                <div class="mt-4 flex flex-col sm:flex-row gap-2">
                    <PrimaryButton
                        class="sm:mr-2"
                        @click="router.visit(route('posts.index'))"
                    >
                        Pokaż wszystkie posty
                    </PrimaryButton>
                    <PrimaryButton @click="onFocusOut">Anuluj</PrimaryButton>
                </div>
            </div>
        </transition>
    </div>
</template>
