// react-forum/resources/js/Components/PostTile.jsx
import { useEffect } from "react";
import { Link, usePage } from "@inertiajs/react";
import PostLabels from "./PostLabels";

const PostTile = ({ post }) => {
    const page = usePage();
    const isAuthor = post.user.id === page.props?.auth?.user?.id;

    performance.mark("PostTileStartRender");

    useEffect(() => {
        performance.mark("PostTileEndRender");

        const measure = performance.measure(
            "PostTileMeasureRender",
            "PostTileStartRender",
            "PostTileEndRender"
        );
        console.log(
            `Total time for PostTile render: ${measure.duration} ms, component complexity: 2`
        );
    }, []);

    return (
        <div className="bg-white rounded-lg shadow-md p-4 w-full">
            <Link href={route("posts.show", { post })}>
                <h3 className="text-lg font-semibold mb-2 hover:text-gray-500">
                    {post.title}
                </h3>
            </Link>

            <p className={`text-gray-600 ${isAuthor ? "text-blue-600" : ""}`}>
                Autor: {post.user.name}
                {isAuthor && <span>(Twój post)</span>}
            </p>

            <p className="text-gray-600">Kategorie:</p>
            <PostLabels labels={post.categories} />

            <p className="text-gray-600">Tagi:</p>
            <PostLabels labels={post.tags} isTagLabel />
        </div>
    );
};

export default PostTile;

// vue-forum/resources/js/Components/PostTile.vue
<script setup>
import { onMounted, onBeforeMount } from "vue";
import { Link } from "@inertiajs/vue3";
import PostLabels from "./PostLabels.vue";

defineProps({
    post: { type: Object, required: true },
});

onBeforeMount(() => {
    performance.mark("PostTileStartRender");
});

onMounted(() => {
    performance.mark("PostTileEndRender");

    const measure = performance.measure(
        "PostTileMeasureRender",
        "PostTileStartRender",
        "PostTileEndRender"
    );
    console.log(`Total time for PostTile render: ${measure.duration} ms, 
component complexity: 2`);
});
</script>

<template>
    <div class="bg-white rounded-lg shadow-md p-4 w-full">
        <Link :href="route('posts.show', { post })">
            <h3 class="text-lg font-semibold mb-2 hover:text-gray-500">
                {{ post.title }}
            </h3></Link
        >

        <p
            class="text-gray-600"
            :class="{
                'text-blue-600': post.user.id === $page.props?.auth?.user?.id,
            }"
        >
            Autor: {{ post.user.name }}
            <span v-if="post.user.id === $page.props?.auth?.user?.id"
                >(Twój post)</span
            >
        </p>
        <p class="text-gray-600">Kategorie:</p>
        <PostLabels :labels="post.categories" />
        <p class="text-gray-600">Tagi:</p>
        <PostLabels :labels="post.tags" isTagLabel />
    </div>
</template>
