// vue-forum/resources/js/Components/DangerButton.vue
<script setup>
import { onBeforeMount, onMounted } from "vue";

onBeforeMount(() => {
    performance.mark("DangerButtonStartRender");
});

onMounted(() => {
    performance.mark("DangerButtonEndRender");

    const measure = performance.measure(
        "DangerButtonMeasureRender",
        "DangerButtonStartRender",
        "DangerButtonEndRender"
    );
    console.log(`Total time for DangerButton render: ${measure.duration} ms, 
component complexity: 1`);
});
</script>
<template>
    <button
        class="inline-flex items-center px-4 py-2 bg-red-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-red-500 active:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 transition ease-in-out duration-150"
    >
        <slot />
    </button>
</template>

// react-forum/resources/js/Components/DangerButton.jsx
import { useEffect } from "react";

export default function DangerButton({
    className = "",
    disabled,
    children,
    ...props
}) {
    performance.mark("DangerButtonStartRender");

    useEffect(() => {
        performance.mark("DangerButtonEndRender");

        const measure = performance.measure(
            "DangerButtonMeasureRender",
            "DangerButtonStartRender",
            "DangerButtonEndRender"
        );
        console.log(
            `Total time for DangerButton render: ${measure.duration} ms, component complexity: 1`
        );
    }, []);
    return (
        <button
            {...props}
            className={
                `inline-flex items-center px-4 py-2 bg-red-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-red-500 active:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 transition ease-in-out duration-150 ${
                    disabled && "opacity-25"
                } ` + className
            }
            disabled={disabled}
        >
            {children}
        </button>
    );
}
