// vue-forum/resources/js/Components/ResponsiveNavLink.vue
<script setup>
import { computed, onBeforeMount, onMounted } from "vue";
import { Link } from "@inertiajs/vue3";

const props = defineProps({
    href: {
        type: String,
        required: true,
    },
    active: {
        type: Boolean,
    },
});

onBeforeMount(() => {
    performance.mark("ResponsiveNavLinkStartRender");
});

onMounted(() => {
    performance.mark("ResponsiveNavLinkEndRender");

    const measure = performance.measure(
        "ResponsiveNavLinkMeasureRender",
        "ResponsiveNavLinkStartRender",
        "ResponsiveNavLinkEndRender"
    );
    console.log(
        `Total time for ResponsiveNavLink render: ${measure.duration} ms, 
component complexity: 1`
    );
});

const classes = computed(() =>
    props.active
        ? "block w-full ps-3 pe-4 py-2 border-l-4 border-indigo-400 text-start text-base font-medium text-indigo-700 bg-indigo-50 focus:outline-none focus:text-indigo-800 focus:bg-indigo-100 focus:border-indigo-700 transition duration-150 ease-in-out"
        : "block w-full ps-3 pe-4 py-2 border-l-4 border-transparent text-start text-base font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300 focus:outline-none focus:text-gray-800 focus:bg-gray-50 focus:border-gray-300 transition duration-150 ease-in-out"
);
</script>

<template>
    <Link :href="href" :class="classes">
        <slot />
    </Link>
</template>

// react-forum/resources/js/Components/ResponsiveNavLink.jsx
import { Link } from "@inertiajs/react";
import { useEffect } from "react";

export default function ResponsiveNavLink({
    active = false,
    className = "",
    children,
    ...props
}) {
    performance.mark("ResponsiveNavLinkStartRender");

    useEffect(() => {
        performance.mark("ResponsiveNavLinkEndRender");

        const measure = performance.measure(
            "ResponsiveNavLinkMeasureRender",
            "ResponsiveNavLinkStartRender",
            "ResponsiveNavLinkEndRender"
        );
        console.log(
            `Total time for ResponsiveNavLink render: ${measure.duration} ms, component complexity: 1`
        );
    }, []);
    return (
        <Link
            {...props}
            className={`w-full flex items-start ps-3 pe-4 py-2 border-l-4 ${
                active
                    ? "border-indigo-400 text-indigo-700 bg-indigo-50 focus:text-indigo-800 focus:bg-indigo-100 focus:border-indigo-700"
                    : "border-transparent text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300 focus:text-gray-800 focus:bg-gray-50 focus:border-gray-300"
            } text-base font-medium focus:outline-none transition duration-150 ease-in-out ${className}`}
        >
            {children}
        </Link>
    );
}
